services:
  postgres:
    image: postgres:13
    container_name: rahnema_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - rahnema_network
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./data/pg/data:/var/lib/postgresql/data
      - ./data/pg/init:/docker-entrypoint-initdb.d
      - ./data/pg/init-data:/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5

  redis:
    image: redis:7.2-bookworm
    container_name: rahnema_redis
    networks:
      - rahnema_network
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5

  redis_postgres_syncer:
    build:
      context: ./app
    container_name: redis_postgres_syncer
    networks:
      - rahnema_network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

networks:
  rahnema_network:
    driver: bridge

volumes:
  redis_data:
    external: false
  postgres_data:
    external: false